version: "2"
services:
  drupal:
    image: kmoonwright/custom-drupal
    ports:
      - 8080:80
  postgresql:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=1234567
    volumes: 
      - drupal-data:/var/lib/postgresql/data
volumes: 
  drupal-data: